"""base schema

Revision ID: 31a44dd9894b
Revises:
Create Date: 2026-09-15 11:52:28.961506+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.infrastructure.db.models import IMMUTABLE_TABLES

revision: str = "31a44dd9894b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{0,126}[a-z0-9]$'", name=op.f("ck_projects_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')", name=op.f("ck_projects_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("slug", name="uq_projects_slug"),
    )
    op.create_index(
        "uq_projects_is_default",
        "projects",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "auth_provider", sa.String(length=64), server_default=sa.text("'local'"), nullable=False
        ),
        sa.Column("external_subject", sa.String(length=256), nullable=True),
        sa.Column(
            "role", sa.String(length=64), server_default=sa.text("'researcher'"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("session_epoch", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('admin', 'researcher')", name=op.f("ck_users_role_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_audit_events_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_actor_id_created_at",
        "audit_events",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_created_at",
        "audit_events",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_target_type_target_id_created_at",
        "audit_events",
        ["target_type", "target_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{0,126}[a-z0-9]$'", name=op.f("ck_pipelines_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')", name=op.f("ck_pipelines_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_pipelines_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_pipelines_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipelines")),
        sa.UniqueConstraint("project_id", "slug", name="uq_pipelines_project_id_slug"),
    )
    op.create_index(op.f("ix_pipelines_project_id"), "pipelines", ["project_id"], unique=False)
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=64), server_default=sa.text("'member'"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner', 'admin', 'member', 'viewer')",
            name=op.f("ck_project_members_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_project_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "user_id", name=op.f("pk_project_members")),
    )
    op.create_table(
        "publications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("current_revision_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'draft'"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{0,126}[a-z0-9]$'", name=op.f("ck_publications_slug_format")
        ),
        sa.CheckConstraint(
            "status <> 'published' OR current_revision_id IS NOT NULL",
            name=op.f("ck_publications_published_has_revision"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_publications_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_publications_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"],
            ["publication_revisions.id"],
            name=op.f("fk_publications_current_revision_id_publication_revisions"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_publications_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publications")),
        sa.UniqueConstraint("project_id", "slug", name="uq_publications_project_id_slug"),
    )
    op.create_index(
        op.f("ix_publications_project_id"), "publications", ["project_id"], unique=False
    )
    op.create_table(
        "runtime_environments",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("venv_path", sa.String(length=1024), nullable=False),
        sa.Column("python_version", sa.String(length=32), nullable=True),
        sa.Column("image_ref", sa.String(length=512), nullable=False),
        sa.Column(
            "contract_versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'building'"), nullable=False
        ),
        sa.Column("is_default", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_reason", sa.String(length=256), nullable=True),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('building', 'available', 'deprecated', 'failed')",
            name=op.f("ck_runtime_environments_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runtime_environments_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runtime_environments")),
        sa.UniqueConstraint("project_id", "name", name="uq_runtime_environments_project_id_name"),
    )
    op.create_index(
        "uq_runtime_environments_default",
        "runtime_environments",
        ["project_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "saved_values",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type_key", sa.String(length=128), nullable=False),
        sa.Column(
            "type_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "container", sa.String(length=16), server_default=sa.text("'single'"), nullable=False
        ),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "container IN ('single', 'list', 'map')", name=op.f("ck_saved_values_container_valid")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_saved_values_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_saved_values_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_values")),
        sa.UniqueConstraint(
            "user_id",
            "type_key",
            "container",
            "name",
            name="uq_saved_values_user_id_type_key_container_name",
        ),
    )
    op.create_index("ix_saved_values_type_key", "saved_values", ["type_key"], unique=False)
    op.create_index(op.f("ix_saved_values_user_id"), "saved_values", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("session_epoch", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name="uq_sessions_token_hash"),
    )
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_table(
        "shared_storage_roots",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("root_path", sa.String(length=1024), nullable=False),
        sa.Column("readable", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("writable", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "identity_mode",
            sa.String(length=32),
            server_default=sa.text("'service_account'"),
            nullable=False,
        ),
        sa.Column("attested_by", sa.UUID(), nullable=True),
        sa.Column("attested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attestation_note", sa.String(length=512), nullable=True),
        sa.Column(
            "metadata_",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "identity_mode <> 'service_account' OR (attested_by IS NOT NULL AND attested_at IS NOT NULL)",
            name=op.f("ck_shared_storage_roots_service_account_root_is_attested"),
        ),
        sa.CheckConstraint(
            "identity_mode IN ('service_account', 'requesting_user')",
            name=op.f("ck_shared_storage_roots_identity_mode_valid"),
        ),
        sa.CheckConstraint(
            "readable OR writable", name=op.f("ck_shared_storage_roots_some_access")
        ),
        sa.ForeignKeyConstraint(
            ["attested_by"],
            ["users.id"],
            name=op.f("fk_shared_storage_roots_attested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_shared_storage_roots_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_shared_storage_roots")),
    )
    op.create_table(
        "type_definitions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("source_ref", sa.String(length=512), nullable=True),
        sa.Column(
            "source", sa.String(length=32), server_default=sa.text("'authored'"), nullable=False
        ),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('authored', 'imported_python', 'imported_legacy')",
            name=op.f("ck_type_definitions_source_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')",
            name=op.f("ck_type_definitions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_type_definitions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_type_definitions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_type_definitions")),
        sa.UniqueConstraint("project_id", "key", name="uq_type_definitions_project_id_key"),
    )
    op.create_index(
        op.f("ix_type_definitions_project_id"), "type_definitions", ["project_id"], unique=False
    )
    op.create_table(
        "environment_snapshots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=False),
        sa.Column("digest", sa.String(length=80), nullable=False),
        sa.Column("snapshot_path", sa.String(length=1024), nullable=False),
        sa.Column(
            "packages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("reference_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "digest ~ '^sha256:[0-9a-f]{64}$'", name=op.f("ck_environment_snapshots_digest_format")
        ),
        sa.CheckConstraint(
            "reference_count >= 0",
            name=op.f("ck_environment_snapshots_reference_count_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["runtime_environments.id"],
            name=op.f("fk_environment_snapshots_environment_id_runtime_environments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environment_snapshots")),
        sa.UniqueConstraint(
            "environment_id", "digest", name="uq_environment_snapshots_environment_id_digest"
        ),
    )
    op.create_index(
        op.f("ix_environment_snapshots_environment_id"),
        "environment_snapshots",
        ["environment_id"],
        unique=False,
    )
    op.create_index(
        "ix_environment_snapshots_unreferenced",
        "environment_snapshots",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("reference_count = 0"),
    )
    op.create_table(
        "package_operations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("environment_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("operation", sa.String(length=32), nullable=False),
        sa.Column("specifier", sa.String(length=512), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("resulting_digest", sa.String(length=80), nullable=True),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "operation IN ('install', 'uninstall', 'upgrade')",
            name=op.f("ck_package_operations_operation_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_package_operations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_package_operations_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["runtime_environments.id"],
            name=op.f("fk_package_operations_environment_id_runtime_environments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_operations")),
    )
    op.create_index(
        "ix_package_operations_environment_id_created_at",
        "package_operations",
        ["environment_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "pipeline_revisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "source_format", sa.String(length=64), server_default=sa.text("'yaml'"), nullable=False
        ),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column(
            "ir_version", sa.String(length=16), server_default=sa.text("'1.0'"), nullable=False
        ),
        sa.Column(
            "compiled_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "input_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "output_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("graph_hash", sa.String(length=80), nullable=False),
        sa.Column(
            "validation_status",
            sa.String(length=64),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "validation_report",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("runtime_environment_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "graph_hash ~ '^sha256:[0-9a-f]{64}$'",
            name=op.f("ck_pipeline_revisions_graph_hash_format"),
        ),
        sa.CheckConstraint(
            "source_format IN ('yaml', 'json')",
            name=op.f("ck_pipeline_revisions_source_format_valid"),
        ),
        sa.CheckConstraint(
            "validation_status IN ('pending', 'valid', 'invalid')",
            name=op.f("ck_pipeline_revisions_validation_status_valid"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_pipeline_revisions_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_pipeline_revisions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
            name=op.f("fk_pipeline_revisions_pipeline_id_pipelines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["runtime_environment_id"],
            ["runtime_environments.id"],
            name=op.f("fk_pipeline_revisions_runtime_environment_id_runtime_environments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_revisions")),
        sa.UniqueConstraint(
            "pipeline_id", "version", name="uq_pipeline_revisions_pipeline_id_version"
        ),
    )
    op.create_index(
        "ix_pipeline_revisions_graph_hash", "pipeline_revisions", ["graph_hash"], unique=False
    )
    op.create_index(
        op.f("ix_pipeline_revisions_pipeline_id"),
        "pipeline_revisions",
        ["pipeline_id"],
        unique=False,
    )
    op.create_table(
        "workers",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("hostname", sa.String(length=256), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("runtime_environment_id", sa.UUID(), nullable=True),
        sa.Column("capacity", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'starting'"), nullable=False
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('starting', 'active', 'draining', 'stopped')",
            name=op.f("ck_workers_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["runtime_environment_id"],
            ["runtime_environments.id"],
            name=op.f("fk_workers_runtime_environment_id_runtime_environments"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workers")),
    )
    op.create_index(
        "ix_workers_status_last_heartbeat_at",
        "workers",
        ["status", "last_heartbeat_at"],
        unique=False,
    )
    op.create_table(
        "pipeline_inputs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pipeline_revision_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("type_ref", sa.String(length=128), nullable=True),
        sa.Column("primitive_type", sa.String(length=64), nullable=False),
        sa.Column("required", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("default_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "primitive_type IN ('string', 'integer', 'number', 'boolean', 'enum', 'file', 'directory', 'url', 'object', 'array')",
            name=op.f("ck_pipeline_inputs_primitive_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_revision_id"],
            ["pipeline_revisions.id"],
            name=op.f("fk_pipeline_inputs_pipeline_revision_id_pipeline_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_inputs")),
        sa.UniqueConstraint(
            "pipeline_revision_id", "key", name="uq_pipeline_inputs_pipeline_revision_id_key"
        ),
    )
    op.create_index(
        op.f("ix_pipeline_inputs_pipeline_revision_id"),
        "pipeline_inputs",
        ["pipeline_revision_id"],
        unique=False,
    )
    op.create_table(
        "pipeline_outputs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pipeline_revision_id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column(
            "artifact_kind",
            sa.String(length=64),
            server_default=sa.text("'task_output'"),
            nullable=False,
        ),
        sa.Column(
            "visibility", sa.String(length=64), server_default=sa.text("'private'"), nullable=False
        ),
        sa.Column(
            "delivery_modes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "retention_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_kind IN ('upload_input', 'shared_input_reference', 'url_input', 'task_output', 'run_output_package', 'task_log', 'manifest', 'diagnostic')",
            name=op.f("ck_pipeline_outputs_artifact_kind_valid"),
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'project', 'public')",
            name=op.f("ck_pipeline_outputs_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_revision_id"],
            ["pipeline_revisions.id"],
            name=op.f("fk_pipeline_outputs_pipeline_revision_id_pipeline_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_outputs")),
        sa.UniqueConstraint(
            "pipeline_revision_id", "key", name="uq_pipeline_outputs_pipeline_revision_id_key"
        ),
    )
    op.create_index(
        op.f("ix_pipeline_outputs_pipeline_revision_id"),
        "pipeline_outputs",
        ["pipeline_revision_id"],
        unique=False,
    )
    op.create_table(
        "publication_revisions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("publication_id", sa.UUID(), nullable=False),
        sa.Column("pipeline_revision_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "display_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "access_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_publication_revisions_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_publication_revisions_created_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_revision_id"],
            ["pipeline_revisions.id"],
            name=op.f("fk_publication_revisions_pipeline_revision_id_pipeline_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publications.id"],
            name=op.f("fk_publication_revisions_publication_id_publications"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_revisions")),
        sa.UniqueConstraint(
            "publication_id", "version", name="uq_publication_revisions_publication_id_version"
        ),
    )
    op.create_index(
        "ix_publication_revisions_description_trgm",
        "publication_revisions",
        ["description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_publication_revisions_pipeline_revision_id"),
        "publication_revisions",
        ["pipeline_revision_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publication_revisions_publication_id"),
        "publication_revisions",
        ["publication_id"],
        unique=False,
    )
    op.create_index(
        "ix_publication_revisions_title_trgm",
        "publication_revisions",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "publication_fields",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("publication_revision_id", sa.UUID(), nullable=False),
        sa.Column("binding_target", sa.String(length=64), nullable=False),
        sa.Column("binding_stage", sa.String(length=128), nullable=True),
        sa.Column("binding_step", sa.String(length=128), nullable=True),
        sa.Column("binding_key", sa.String(length=128), nullable=False),
        sa.Column("binding_value_type", sa.String(length=32), nullable=True),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("label", sa.String(length=256), nullable=False),
        sa.Column("help_text", sa.Text(), nullable=True),
        sa.Column("placeholder", sa.String(length=256), nullable=True),
        sa.Column("field_type", sa.String(length=64), nullable=False),
        sa.Column("type_ref", sa.String(length=128), nullable=True),
        sa.Column("required", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("order_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("ui_group", sa.String(length=128), nullable=True),
        sa.Column("default_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fixed_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "constraints",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "source_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "delivery_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "save_policy",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "visibility", sa.String(length=64), server_default=sa.text("'visible'"), nullable=False
        ),
        sa.CheckConstraint(
            "(binding_target = 'default_value' AND binding_key IS NOT NULL    AND binding_stage IS NULL AND binding_step IS NULL) OR (binding_target = 'step_parameter' AND binding_stage IS NOT NULL    AND binding_step IS NOT NULL AND binding_key IS NOT NULL) OR (binding_target IN ('stage_input', 'stage_output')    AND binding_stage IS NOT NULL AND binding_key IS NOT NULL    AND binding_step IS NULL)",
            name=op.f("ck_publication_fields_binding_coordinates_match_target"),
        ),
        sa.CheckConstraint(
            "binding_target IN ('default_value', 'step_parameter', 'stage_input', 'stage_output')",
            name=op.f("ck_publication_fields_binding_target_valid"),
        ),
        sa.CheckConstraint(
            "field_type IN ('string', 'integer', 'number', 'boolean', 'enum', 'file', 'directory', 'url', 'object', 'array')",
            name=op.f("ck_publication_fields_field_type_valid"),
        ),
        sa.CheckConstraint(
            "fixed_value IS NULL OR visibility = 'hidden'",
            name=op.f("ck_publication_fields_fixed_value_is_hidden"),
        ),
        sa.CheckConstraint(
            "visibility IN ('visible', 'hidden', 'readonly')",
            name=op.f("ck_publication_fields_visibility_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["publication_revision_id"],
            ["publication_revisions.id"],
            name=op.f("fk_publication_fields_publication_revision_id_publication_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_fields")),
        sa.UniqueConstraint(
            "publication_revision_id",
            "key",
            name="uq_publication_fields_publication_revision_id_key",
        ),
    )
    op.create_index(
        "ix_publication_fields_publication_revision_id_order_index",
        "publication_fields",
        ["publication_revision_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("publication_revision_id", sa.UUID(), nullable=True),
        sa.Column("pipeline_revision_id", sa.UUID(), nullable=False),
        sa.Column("requested_by", sa.UUID(), nullable=False),
        sa.Column(
            "requested_from",
            sa.String(length=64),
            server_default=sa.text("'manual'"),
            nullable=False,
        ),
        sa.Column("environment_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "input_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "compiled_run_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "requested_from IN ('manual', 'schedule', 'api', 'admin')",
            name=op.f("ck_runs_requested_from_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'blocked', 'cancel_requested', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "(cancel_requested_at IS NULL) = (cancel_requested_by IS NULL)",
            name=op.f("ck_runs_cancel_fields_together"),
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR started_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_runs_finished_after_started"),
        ),
        sa.ForeignKeyConstraint(
            ["cancel_requested_by"],
            ["users.id"],
            name=op.f("fk_runs_cancel_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["environment_snapshot_id"],
            ["environment_snapshots.id"],
            name=op.f("fk_runs_environment_snapshot_id_environment_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_revision_id"],
            ["pipeline_revisions.id"],
            name=op.f("fk_runs_pipeline_revision_id_pipeline_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_runs_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["publication_revision_id"],
            ["publication_revisions.id"],
            name=op.f("fk_runs_publication_revision_id_publication_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"],
            ["users.id"],
            name=op.f("fk_runs_requested_by_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
    )
    op.create_index(
        "ix_runs_cancel_requested_at",
        "runs",
        ["cancel_requested_at"],
        unique=False,
        postgresql_where=sa.text("status = 'cancel_requested'"),
    )
    op.create_index(
        op.f("ix_runs_pipeline_revision_id"), "runs", ["pipeline_revision_id"], unique=False
    )
    op.create_index(
        "ix_runs_project_id_created_at",
        "runs",
        ["project_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_runs_publication_revision_id"), "runs", ["publication_revision_id"], unique=False
    )
    op.create_index(
        "ix_runs_requested_by_created_at",
        "runs",
        ["requested_by", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index("ix_runs_status_updated_at", "runs", ["status", "updated_at"], unique=False)
    op.create_index(
        "uq_runs_requested_by_idempotency_key",
        "runs",
        ["requested_by", "idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_table(
        "run_tasks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("stage_key", sa.String(length=128), nullable=False),
        sa.Column("task_key", sa.String(length=256), nullable=False),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'created'"), nullable=False
        ),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "dependencies_satisfied", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "task_spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "task_class", sa.String(length=64), server_default=sa.text("'standard'"), nullable=False
        ),
        sa.Column(
            "cpu_request_millicores", sa.Integer(), server_default=sa.text("1000"), nullable=False
        ),
        sa.Column(
            "memory_request_bytes",
            sa.BigInteger(),
            server_default=sa.text("2147483648"),
            nullable=False,
        ),
        sa.Column(
            "wall_time_limit_seconds", sa.Integer(), server_default=sa.text("21600"), nullable=False
        ),
        sa.Column("exclusive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("claimed_by", sa.String(length=256), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_retries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('created', 'queued', 'claimed', 'running', 'retry_wait', 'succeeded', 'failed', 'cancelled', 'skipped')",
            name=op.f("ck_run_tasks_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('claimed', 'running') OR (claimed_by IS NOT NULL AND lease_expires_at IS NOT NULL)",
            name=op.f("ck_run_tasks_held_task_has_lease"),
        ),
        sa.CheckConstraint(
            "task_class IN ('small', 'standard', 'large', 'exclusive')",
            name=op.f("ck_run_tasks_task_class_valid"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0", name=op.f("ck_run_tasks_attempt_count_non_negative")
        ),
        sa.CheckConstraint(
            "cpu_request_millicores > 0", name=op.f("ck_run_tasks_cpu_request_positive")
        ),
        sa.CheckConstraint("max_retries >= 0", name=op.f("ck_run_tasks_max_retries_non_negative")),
        sa.CheckConstraint(
            "memory_request_bytes > 0", name=op.f("ck_run_tasks_memory_request_positive")
        ),
        sa.CheckConstraint("retry_count >= 0", name=op.f("ck_run_tasks_retry_count_non_negative")),
        sa.CheckConstraint(
            "wall_time_limit_seconds > 0", name=op.f("ck_run_tasks_wall_time_limit_positive")
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by"],
            ["workers.id"],
            name=op.f("fk_run_tasks_claimed_by_workers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_tasks_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_tasks")),
        sa.UniqueConstraint("run_id", "task_key", name="uq_run_tasks_run_id_task_key"),
    )
    op.create_index(
        "ix_run_tasks_admission",
        "run_tasks",
        ["cpu_request_millicores", "memory_request_bytes"],
        unique=False,
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.create_index(
        "ix_run_tasks_claimable",
        "run_tasks",
        [sa.literal_column("priority DESC"), "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.create_index(
        "ix_run_tasks_lease_expires_at",
        "run_tasks",
        ["lease_expires_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.create_index(
        "ix_run_tasks_next_retry_at",
        "run_tasks",
        ["next_retry_at"],
        unique=False,
        postgresql_where=sa.text("status = 'retry_wait'"),
    )
    op.create_index("ix_run_tasks_run_id_status", "run_tasks", ["run_id", "status"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("publication_revision_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("rrule", sa.String(length=512), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "timezone", sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False
        ),
        sa.Column(
            "dst_policy",
            sa.String(length=32),
            server_default=sa.text("'skip_nonexistent'"),
            nullable=False,
        ),
        sa.Column(
            "catchup_policy",
            sa.String(length=64),
            server_default=sa.text("'skip_missed'"),
            nullable=False,
        ),
        sa.Column(
            "overlap_policy", sa.String(length=64), server_default=sa.text("'skip'"), nullable=False
        ),
        sa.Column("max_concurrent_runs", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "input_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("next_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fire_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_id", sa.UUID(), nullable=True),
        sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "catchup_policy IN ('skip_missed', 'run_once', 'run_all')",
            name=op.f("ck_schedules_catchup_policy_valid"),
        ),
        sa.CheckConstraint(
            "dst_policy IN ('skip_nonexistent', 'shift_forward', 'utc_only')",
            name=op.f("ck_schedules_dst_policy_valid"),
        ),
        sa.CheckConstraint(
            "overlap_policy IN ('skip', 'queue', 'allow')",
            name=op.f("ck_schedules_overlap_policy_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused', 'archived')", name=op.f("ck_schedules_status_valid")
        ),
        sa.CheckConstraint(
            "end_at IS NULL OR end_at > created_at", name=op.f("ck_schedules_end_after_start")
        ),
        sa.CheckConstraint(
            "interval_seconds IS NULL OR interval_seconds >= 60",
            name=op.f("ck_schedules_interval_at_least_a_minute"),
        ),
        sa.CheckConstraint(
            "max_concurrent_runs > 0", name=op.f("ck_schedules_max_concurrent_runs_positive")
        ),
        sa.CheckConstraint(
            "num_nonnulls(rrule, interval_seconds) = 1",
            name=op.f("ck_schedules_exactly_one_recurrence"),
        ),
        sa.ForeignKeyConstraint(
            ["last_run_id"],
            ["runs.id"],
            name=op.f("fk_schedules_last_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_schedules_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_schedules_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["publication_revision_id"],
            ["publication_revisions.id"],
            name=op.f("fk_schedules_publication_revision_id_publication_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_index("ix_schedules_owner_id", "schedules", ["owner_id"], unique=False)
    op.create_index(
        op.f("ix_schedules_publication_revision_id"),
        "schedules",
        ["publication_revision_id"],
        unique=False,
    )
    op.create_index(
        "ix_schedules_status_next_fire_at",
        "schedules",
        ["status", "next_fire_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "workspaces",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("root_key", sa.String(length=1024), nullable=False),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column("quota_bytes", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'packaged', 'expired', 'deleted')",
            name=op.f("ck_workspaces_status_valid"),
        ),
        sa.CheckConstraint("quota_bytes > 0", name=op.f("ck_workspaces_quota_positive")),
        sa.CheckConstraint("used_bytes >= 0", name=op.f("ck_workspaces_used_non_negative")),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_workspaces_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("run_id", name="uq_workspaces_run_id"),
    )
    op.create_index(
        "ix_workspaces_expires_at",
        "workspaces",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "run_task_attempts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=256), nullable=True),
        sa.Column("container_id", sa.String(length=128), nullable=True),
        sa.Column("image_ref", sa.String(length=512), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'running'"), nullable=False
        ),
        sa.Column("log_artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed', 'cancelled', 'lost', 'timed_out')",
            name=op.f("ck_run_task_attempts_status_valid"),
        ),
        sa.CheckConstraint(
            "attempt_number > 0", name=op.f("ck_run_task_attempts_attempt_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["log_artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_run_task_attempts_log_artifact_id_artifacts"),
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["run_tasks.id"],
            name=op.f("fk_run_task_attempts_task_id_run_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["workers.id"],
            name=op.f("fk_run_task_attempts_worker_id_workers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_task_attempts")),
        sa.UniqueConstraint(
            "task_id", "attempt_number", name="uq_run_task_attempts_task_id_attempt_number"
        ),
    )
    op.create_index(
        "ix_run_task_attempts_container_id",
        "run_task_attempts",
        ["container_id"],
        unique=False,
        postgresql_where=sa.text("container_id IS NOT NULL AND status = 'running'"),
    )
    op.create_index(
        op.f("ix_run_task_attempts_task_id"), "run_task_attempts", ["task_id"], unique=False
    )
    op.create_table(
        "run_task_dependencies",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_task_id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "task_id <> depends_on_task_id",
            name=op.f("ck_run_task_dependencies_no_self_dependency"),
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_task_id"],
            ["run_tasks.id"],
            name=op.f("fk_run_task_dependencies_depends_on_task_id_run_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["run_tasks.id"],
            name=op.f("fk_run_task_dependencies_task_id_run_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "depends_on_task_id", name=op.f("pk_run_task_dependencies")
        ),
    )
    op.create_index(
        "ix_run_task_dependencies_depends_on_task_id",
        "run_task_dependencies",
        ["depends_on_task_id"],
        unique=False,
    )
    op.create_table(
        "schedule_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_schedule_events_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_schedule_events_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_events_schedule_id_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_events")),
    )
    op.create_index(
        "ix_schedule_events_schedule_id_created_at",
        "schedule_events",
        ["schedule_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "schedule_fires",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("fire_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=64), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('created', 'skipped_overlap', 'skipped_catchup', 'failed')",
            name=op.f("ck_schedule_fires_outcome_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_schedule_fires_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_fires_schedule_id_schedules"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_fires")),
        sa.UniqueConstraint("schedule_id", "fire_at", name="uq_schedule_fires_schedule_id_fire_at"),
    )
    op.create_index(
        "ix_schedule_fires_schedule_id_fire_at",
        "schedule_fires",
        ["schedule_id", sa.literal_column("fire_at DESC")],
        unique=False,
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("task_attempt_id", sa.UUID(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "storage_backend",
            sa.String(length=64),
            server_default=sa.text("'posix'"),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "visibility", sa.String(length=64), server_default=sa.text("'private'"), nullable=False
        ),
        sa.Column(
            "retention_class",
            sa.String(length=64),
            server_default=sa.text("'standard'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("purged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_artifacts_checksum_format"),
        ),
        sa.CheckConstraint(
            "kind IN ('upload_input', 'shared_input_reference', 'url_input', 'task_output', 'run_output_package', 'task_log', 'manifest', 'diagnostic')",
            name=op.f("ck_artifacts_kind_valid"),
        ),
        sa.CheckConstraint(
            "retention_class IN ('ephemeral', 'standard', 'long_term', 'permanent')",
            name=op.f("ck_artifacts_retention_class_valid"),
        ),
        sa.CheckConstraint(
            "storage_backend IN ('posix', 's3')", name=op.f("ck_artifacts_storage_backend_valid")
        ),
        sa.CheckConstraint(
            "visibility IN ('private', 'project', 'public')",
            name=op.f("ck_artifacts_visibility_valid"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_artifacts_size_non_negative")),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_artifacts_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_artifacts_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_artifacts_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["task_attempt_id"],
            ["run_task_attempts.id"],
            name=op.f("fk_artifacts_task_attempt_id_run_task_attempts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["run_tasks.id"],
            name=op.f("fk_artifacts_task_id_run_tasks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(
        "ix_artifacts_expires_at",
        "artifacts",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL AND expires_at IS NOT NULL"),
    )
    op.create_index(
        "ix_artifacts_run_id_kind_created_at",
        "artifacts",
        ["run_id", "kind", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_artifacts_storage_backend_storage_key",
        "artifacts",
        ["storage_backend", "storage_key"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "artifact_access_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("access_type", sa.String(length=32), nullable=False),
        sa.Column("bytes_served", sa.Integer(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "access_type IN ('download', 'range_download', 'metadata', 'denied')",
            name=op.f("ck_artifact_access_events_access_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_artifact_access_events_actor_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_artifact_access_events_artifact_id_artifacts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifact_access_events")),
    )
    op.create_index(
        "ix_artifact_access_events_actor_id_created_at",
        "artifact_access_events",
        ["actor_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_artifact_access_events_artifact_id_created_at",
        "artifact_access_events",
        ["artifact_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "run_deliveries",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("target_root_id", sa.String(length=128), nullable=True),
        sa.Column("target_path", sa.String(length=1024), nullable=True),
        sa.Column(
            "status", sa.String(length=64), server_default=sa.text("'pending'"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mode <> 'shared' OR target_root_id IS NOT NULL",
            name=op.f("ck_run_deliveries_shared_has_target_root"),
        ),
        sa.CheckConstraint(
            "mode IN ('download', 'shared')", name=op.f("ck_run_deliveries_mode_valid")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'delivered', 'failed', 'skipped')",
            name=op.f("ck_run_deliveries_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_run_deliveries_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_run_deliveries_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_deliveries_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_deliveries")),
        sa.UniqueConstraint(
            "run_id", "field_key", "mode", name="uq_run_deliveries_run_id_field_key_mode"
        ),
    )
    op.create_index(
        "ix_run_deliveries_status_run_id", "run_deliveries", ["status", "run_id"], unique=False
    )
    op.create_table(
        "run_field_values",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("value_source", sa.String(length=32), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value_source IN ('researcher', 'default', 'fixed', 'schedule', 'import')",
            name=op.f("ck_run_field_values_value_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_run_field_values_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_field_values_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_field_values")),
        sa.UniqueConstraint("run_id", "field_key", name="uq_run_field_values_run_id_field_key"),
    )
    op.create_index(
        op.f("ix_run_field_values_run_id"), "run_field_values", ["run_id"], unique=False
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("declared_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("received_bytes", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=64), server_default=sa.text("'open'"), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status <> 'completed' OR artifact_id IS NOT NULL",
            name=op.f("ck_uploads_completed_has_artifact"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'completed', 'aborted', 'expired')",
            name=op.f("ck_uploads_status_valid"),
        ),
        sa.CheckConstraint(
            "declared_size_bytes IS NULL OR received_bytes <= declared_size_bytes",
            name=op.f("ck_uploads_not_over_declared_size"),
        ),
        sa.CheckConstraint("received_bytes >= 0", name=op.f("ck_uploads_received_non_negative")),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["artifacts.id"],
            name=op.f("fk_uploads_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_uploads_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_uploads_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_uploads")),
    )
    op.create_index(
        "ix_uploads_owner_id_created_at", "uploads", ["owner_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_uploads_status_expires_at",
        "uploads",
        ["status", "expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###

    # --- hand-written DDL (see scripts/dev/append_base_migration_sql.py) ---
    # --- circular foreign keys -------------------------------------------
    #
    # Alembic autogenerate does NOT emit use_alter foreign keys, so without
    # these two statements the columns have no referential integrity at all
    # and `alembic check` reports them as missing forever. Both close a cycle:
    # a publication points at its current revision while every revision points
    # back at its publication, and an attempt points at its log artifact while
    # an artifact points back at the attempt that produced it.
    op.create_foreign_key(
        "fk_publications_current_revision_id_publication_revisions",
        "publications",
        "publication_revisions",
        ["current_revision_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_run_task_attempts_log_artifact_id_artifacts",
        "run_task_attempts",
        "artifacts",
        ["log_artifact_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )

    # --- immutability, enforced by the database (G23) ---------------------
    #
    # "Anything used to run work is immutable" is the principle the whole
    # design rests on. Convention does not survive a deadline, so revision
    # tables reject UPDATE and DELETE outright.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION bp_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'Table % is immutable: % is not permitted. Create a new revision instead.',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in IMMUTABLE_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{table}_immutable
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION bp_forbid_mutation();
            """
        )

    # --- a publication may only point at its own revision (G31) -----------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION bp_check_current_revision() RETURNS trigger AS $$
        DECLARE
            owner_id uuid;
        BEGIN
            IF NEW.current_revision_id IS NULL THEN
                RETURN NEW;
            END IF;
            SELECT publication_id INTO owner_id
            FROM publication_revisions
            WHERE id = NEW.current_revision_id;
            IF owner_id IS DISTINCT FROM NEW.id THEN
                RAISE EXCEPTION
                    'current_revision_id % belongs to publication %, not %',
                    NEW.current_revision_id, owner_id, NEW.id
                    USING ERRCODE = 'foreign_key_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_publications_current_revision
        BEFORE INSERT OR UPDATE OF current_revision_id ON publications
        FOR EACH ROW EXECUTE FUNCTION bp_check_current_revision();
        """
    )

    # --- the default project (ADR 0009) -----------------------------------
    op.execute(
        """
        INSERT INTO projects (slug, title, description, status, is_default)
        VALUES (
            'default',
            'Default project',
            'Seeded by the base migration. Single-project deployments use only this row.',
            'active',
            true
        )
        """
    )


def downgrade() -> None:
    # --- hand-written DDL (see scripts/dev/append_base_migration_sql.py) ---
    op.execute("DROP TRIGGER IF EXISTS trg_publications_current_revision ON publications")
    op.execute("DROP FUNCTION IF EXISTS bp_check_current_revision()")
    for table in IMMUTABLE_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
    op.execute("DROP FUNCTION IF EXISTS bp_forbid_mutation()")
    op.drop_constraint(
        "fk_run_task_attempts_log_artifact_id_artifacts", "run_task_attempts", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_publications_current_revision_id_publication_revisions",
        "publications",
        type_="foreignkey",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_uploads_status_expires_at",
        table_name="uploads",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_index("ix_uploads_owner_id_created_at", table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_run_field_values_run_id"), table_name="run_field_values")
    op.drop_table("run_field_values")
    op.drop_index("ix_run_deliveries_status_run_id", table_name="run_deliveries")
    op.drop_table("run_deliveries")
    op.drop_index(
        "ix_artifact_access_events_artifact_id_created_at", table_name="artifact_access_events"
    )
    op.drop_index(
        "ix_artifact_access_events_actor_id_created_at", table_name="artifact_access_events"
    )
    op.drop_table("artifact_access_events")
    op.drop_index(
        "uq_artifacts_storage_backend_storage_key",
        table_name="artifacts",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_artifacts_run_id_kind_created_at", table_name="artifacts")
    op.drop_index(
        "ix_artifacts_expires_at",
        table_name="artifacts",
        postgresql_where=sa.text("deleted_at IS NULL AND expires_at IS NOT NULL"),
    )
    op.drop_table("artifacts")
    op.drop_index("ix_schedule_fires_schedule_id_fire_at", table_name="schedule_fires")
    op.drop_table("schedule_fires")
    op.drop_index("ix_schedule_events_schedule_id_created_at", table_name="schedule_events")
    op.drop_table("schedule_events")
    op.drop_index("ix_run_task_dependencies_depends_on_task_id", table_name="run_task_dependencies")
    op.drop_table("run_task_dependencies")
    op.drop_index(op.f("ix_run_task_attempts_task_id"), table_name="run_task_attempts")
    op.drop_index(
        "ix_run_task_attempts_container_id",
        table_name="run_task_attempts",
        postgresql_where=sa.text("container_id IS NOT NULL AND status = 'running'"),
    )
    op.drop_table("run_task_attempts")
    op.drop_index(
        "ix_workspaces_expires_at",
        table_name="workspaces",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("workspaces")
    op.drop_index(
        "ix_schedules_status_next_fire_at",
        table_name="schedules",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_schedules_publication_revision_id"), table_name="schedules")
    op.drop_index("ix_schedules_owner_id", table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_run_tasks_run_id_status", table_name="run_tasks")
    op.drop_index(
        "ix_run_tasks_next_retry_at",
        table_name="run_tasks",
        postgresql_where=sa.text("status = 'retry_wait'"),
    )
    op.drop_index(
        "ix_run_tasks_lease_expires_at",
        table_name="run_tasks",
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.drop_index(
        "ix_run_tasks_claimable",
        table_name="run_tasks",
        postgresql_where=sa.text("status = 'queued'"),
    )
    op.drop_index(
        "ix_run_tasks_admission",
        table_name="run_tasks",
        postgresql_where=sa.text("status IN ('claimed', 'running')"),
    )
    op.drop_table("run_tasks")
    op.drop_index(
        "uq_runs_requested_by_idempotency_key",
        table_name="runs",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_runs_status_updated_at", table_name="runs")
    op.drop_index("ix_runs_requested_by_created_at", table_name="runs")
    op.drop_index(op.f("ix_runs_publication_revision_id"), table_name="runs")
    op.drop_index("ix_runs_project_id_created_at", table_name="runs")
    op.drop_index(op.f("ix_runs_pipeline_revision_id"), table_name="runs")
    op.drop_index(
        "ix_runs_cancel_requested_at",
        table_name="runs",
        postgresql_where=sa.text("status = 'cancel_requested'"),
    )
    op.drop_table("runs")
    op.drop_index(
        "ix_publication_fields_publication_revision_id_order_index", table_name="publication_fields"
    )
    op.drop_table("publication_fields")
    op.drop_index(
        "ix_publication_revisions_title_trgm",
        table_name="publication_revisions",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_index(
        op.f("ix_publication_revisions_publication_id"), table_name="publication_revisions"
    )
    op.drop_index(
        op.f("ix_publication_revisions_pipeline_revision_id"), table_name="publication_revisions"
    )
    op.drop_index(
        "ix_publication_revisions_description_trgm",
        table_name="publication_revisions",
        postgresql_using="gin",
        postgresql_ops={"description": "gin_trgm_ops"},
    )
    op.drop_table("publication_revisions")
    op.drop_index(op.f("ix_pipeline_outputs_pipeline_revision_id"), table_name="pipeline_outputs")
    op.drop_table("pipeline_outputs")
    op.drop_index(op.f("ix_pipeline_inputs_pipeline_revision_id"), table_name="pipeline_inputs")
    op.drop_table("pipeline_inputs")
    op.drop_index("ix_workers_status_last_heartbeat_at", table_name="workers")
    op.drop_table("workers")
    op.drop_index(op.f("ix_pipeline_revisions_pipeline_id"), table_name="pipeline_revisions")
    op.drop_index("ix_pipeline_revisions_graph_hash", table_name="pipeline_revisions")
    op.drop_table("pipeline_revisions")
    op.drop_index(
        "ix_package_operations_environment_id_created_at", table_name="package_operations"
    )
    op.drop_table("package_operations")
    op.drop_index(
        "ix_environment_snapshots_unreferenced",
        table_name="environment_snapshots",
        postgresql_where=sa.text("reference_count = 0"),
    )
    op.drop_index(
        op.f("ix_environment_snapshots_environment_id"), table_name="environment_snapshots"
    )
    op.drop_table("environment_snapshots")
    op.drop_index(op.f("ix_type_definitions_project_id"), table_name="type_definitions")
    op.drop_table("type_definitions")
    op.drop_table("shared_storage_roots")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_saved_values_user_id"), table_name="saved_values")
    op.drop_index("ix_saved_values_type_key", table_name="saved_values")
    op.drop_table("saved_values")
    op.drop_index(
        "uq_runtime_environments_default",
        table_name="runtime_environments",
        postgresql_where=sa.text("is_default"),
    )
    op.drop_table("runtime_environments")
    op.drop_index(op.f("ix_publications_project_id"), table_name="publications")
    op.drop_table("publications")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_pipelines_project_id"), table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_index("ix_audit_events_target_type_target_id_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_created_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_id_created_at", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index(
        "uq_projects_is_default", table_name="projects", postgresql_where=sa.text("is_default")
    )
    op.drop_table("projects")
    # ### end Alembic commands ###
