"""deliveries belong to an artifact, not a run and a field

A delivery was unique on `(run_id, field_key, mode)`, which reads correctly
until a stage fans out. Six tasks over six plate-reader exports each produce an
output called `results` — six genuinely different files — and the second one to
finish violated the constraint. It did not fail that task: the error raised out
of promotion, out of the worker's claim loop, and stopped every other queued
task with it.

Uniqueness moves to `(artifact_id, mode)`, which is what "deliver this file
there" actually means, and is partial because a delivery may be planned before
its artifact exists. `task_id` is added so a researcher looking at six rows
called `results` can tell which plate each one came from.

Found by the Phase 0b spike; no test had ever run a fan-out end to end.

Revision ID: b6a624ace67e
Revises: 31a44dd9894b
Create Date: 2026-09-16 10:49:45.783075+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b6a624ace67e"
down_revision: str | None = "31a44dd9894b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_deliveries", sa.Column("task_id", sa.UUID(), nullable=True))
    op.drop_constraint(
        op.f("uq_run_deliveries_run_id_field_key_mode"), "run_deliveries", type_="unique"
    )
    op.create_index(op.f("ix_run_deliveries_task_id"), "run_deliveries", ["task_id"], unique=False)
    op.create_index(
        "uq_run_deliveries_artifact_id_mode",
        "run_deliveries",
        ["artifact_id", "mode"],
        unique=True,
        postgresql_where=sa.text("artifact_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_run_deliveries_task_id_run_tasks"),
        "run_deliveries",
        "run_tasks",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_run_deliveries_task_id_run_tasks"), "run_deliveries", type_="foreignkey"
    )
    op.drop_index(
        "uq_run_deliveries_artifact_id_mode",
        table_name="run_deliveries",
        postgresql_where=sa.text("artifact_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_run_deliveries_task_id"), table_name="run_deliveries")
    op.create_unique_constraint(
        op.f("uq_run_deliveries_run_id_field_key_mode"),
        "run_deliveries",
        ["run_id", "field_key", "mode"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("run_deliveries", "task_id")
    # ### end Alembic commands ###
