#!/usr/bin/env python3
"""Append hand-written DDL to the autogenerated base migration.

Alembic autogenerate cannot see extensions, plpgsql triggers, functional
indexes, or seed rows. Keeping them in this script rather than typing them
into the generated file means the base migration can be regenerated during
development without losing them.

Run it once after ``alembic revision --autogenerate``. It is idempotent: a
migration that already carries the block is left alone.
"""

from __future__ import annotations

import pathlib
import sys

MARKER = "# --- hand-written DDL (see scripts/dev/append_base_migration_sql.py) ---"

UPGRADE = f'''
    {MARKER}
    # --- circular foreign keys -------------------------------------------
    #
    # Alembic autogenerate does NOT emit use_alter foreign keys, so without
    # these two statements the columns have no referential integrity at all
    # and `alembic check` reports them as missing forever. Both close a cycle:
    # a publication points at its current revision while every revision points
    # back at its publication, and an attempt points at its log artifact while
    # an artifact points back at the attempt that produced it.
    op.create_foreign_key(
        "fk_publications_current_revision_id_publication_revisions",
        "publications",
        "publication_revisions",
        ["current_revision_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_run_task_attempts_log_artifact_id_artifacts",
        "run_task_attempts",
        "artifacts",
        ["log_artifact_id"],
        ["id"],
        ondelete="RESTRICT",
        use_alter=True,
    )

    # --- immutability, enforced by the database (G23) ---------------------
    #
    # "Anything used to run work is immutable" is the principle the whole
    # design rests on. Convention does not survive a deadline, so revision
    # tables reject UPDATE and DELETE outright.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION bp_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'Table % is immutable: % is not permitted. Create a new revision instead.',
                TG_TABLE_NAME, TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in IMMUTABLE_TABLES:
        op.execute(
            f"""
            CREATE TRIGGER trg_{{table}}_immutable
            BEFORE UPDATE OR DELETE ON {{table}}
            FOR EACH ROW EXECUTE FUNCTION bp_forbid_mutation();
            """
        )

    # --- a publication may only point at its own revision (G31) -----------
    op.execute(
        """
        CREATE OR REPLACE FUNCTION bp_check_current_revision() RETURNS trigger AS $$
        DECLARE
            owner_id uuid;
        BEGIN
            IF NEW.current_revision_id IS NULL THEN
                RETURN NEW;
            END IF;
            SELECT publication_id INTO owner_id
            FROM publication_revisions
            WHERE id = NEW.current_revision_id;
            IF owner_id IS DISTINCT FROM NEW.id THEN
                RAISE EXCEPTION
                    'current_revision_id % belongs to publication %, not %',
                    NEW.current_revision_id, owner_id, NEW.id
                    USING ERRCODE = 'foreign_key_violation';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_publications_current_revision
        BEFORE INSERT OR UPDATE OF current_revision_id ON publications
        FOR EACH ROW EXECUTE FUNCTION bp_check_current_revision();
        """
    )

    # --- the default project (ADR 0009) -----------------------------------
    op.execute(
        """
        INSERT INTO projects (slug, title, description, status, is_default)
        VALUES (
            'default',
            'Default project',
            'Seeded by the base migration. Single-project deployments use only this row.',
            'active',
            true
        )
        """
    )
'''

DOWNGRADE = f"""    {MARKER}
    op.execute("DROP TRIGGER IF EXISTS trg_publications_current_revision ON publications")
    op.execute("DROP FUNCTION IF EXISTS bp_check_current_revision()")
    for table in IMMUTABLE_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{{table}}_immutable ON {{table}}")
    op.execute("DROP FUNCTION IF EXISTS bp_forbid_mutation()")
    op.drop_constraint(
        "fk_run_task_attempts_log_artifact_id_artifacts", "run_task_attempts", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_publications_current_revision_id_publication_revisions",
        "publications",
        type_="foreignkey",
    )
"""

IMPORT_LINE = "from app.infrastructure.db.models import IMMUTABLE_TABLES\n"


def main(path: pathlib.Path) -> int:
    source = path.read_text()
    if MARKER in source:
        print(f"{path.name}: already patched")
        return 0

    if IMPORT_LINE not in source:
        source = source.replace(
            "import sqlalchemy as sa\n",
            f"import sqlalchemy as sa\n\n{IMPORT_LINE}",
            1,
        )

    marker = "\ndef downgrade() -> None:\n"
    index = source.index(marker)
    source = source[:index] + UPGRADE + source[index:]

    index = source.index(marker) + len(marker)
    source = source[:index] + DOWNGRADE + source[index:]

    path.write_text(source)
    print(f"{path.name}: patched")
    return 0


if __name__ == "__main__":
    versions = pathlib.Path(__file__).resolve().parents[2] / "backend/alembic/versions"
    files = sorted(versions.glob("*.py"))
    if len(files) != 1:
        print(
            f"expected exactly one migration in {versions}, found {len(files)}",
            file=sys.stderr,
        )
        raise SystemExit(1)
    raise SystemExit(main(files[0]))
